#include "Fonction.c"
void RemplireStation(STATION*);
void AllocationChargeurs(CHARGEUR**,int);
void AllocationClients(CLIENT**,int);
void AllocationVoitures(VOITURE**,int);
void AllocationPaiements(PAIEMENT**,int);
void RemplireClient(STATION**,int );
void RemplireChargeur(STATION**,int );
void RemplireFichierduTableau(STATION*);
void RemplireTableauDuFichier(STATION*);
void LibereMemoire(STATION*);
void ModifierClient(STATION*);
void ModifierChargeur(STATION*);
void ModifierVoiture(STATION*);
void ModifierPaiement(STATION*);
void AjoutClient(STATION*);
void AjoutChargeur(STATION*);
void AjoutVoiture(STATION*);
void AjoutPaiement(STATION*);
void SupprimerChargeur(STATION*);
void SupprimerClient(STATION*);
void SupprimerVoiture(STATION*);
void SupprimerPaiement(STATION*);
void AfficherClient(STATION*);
void AfficherChargeur(STATION*);
void AfficherPaiement(STATION*);
void AfficherVoiture(STATION*);